<div id="ctcLatin">
<div class="locCtcLandingPageHeader">
<div class="locCtcLandingPageCityWrap">
<div class="locCtcLandingPageCity">Meet [city] Singles Now</div>
<div class="locCtcLandingPage">Call Livelinks, the hottest place to meet the coolest people.</div>
</div>
<div id="locCtcLandingPageForm">[ctc-form-2]</div>
<div class="locCtcLandingPageDisclaimer">In seconds your phone will ring and connect you to local singles. By entering your number above you agree to receive text alerts from Livelinks. Standard Message &amp; Data Rates May Apply. Text STOP to 88999 to cancel. Text HELP to 88999 for help.</div>
</div>
</div>